# YAML pipeline to build and deploy a .NET Core application to Azure App Service

trigger:
- main  # Adjust branch as needed

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Free Trial (77db3f68-d582-4d8b-aade-dbe339640da7)'
  appName: 'test-web-dev'
  resourceGroupName: 'rg-siva'
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.1.x'  # Adjust SDK version as needed

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '<Your NuGet Feed>'  # If using Azure Artifacts for private packages

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    WebAppName: '$(appName)'
    deployToSlotOrASE: true
    ResourceGroupName: '$(resourceGroupName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    enableCustomDeployment: true
    takeAppOfflineFlag: true  # Optionally take app offline during deployment
