# YAML pipeline to build and deploy a .NET Core application to Azure App Service

trigger:
- main  # Adjust branch as needed

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Free Trial (77db3f68-d582-4d8b-aade-dbe339640da7)'
  appName: 'test-web-dev'
  resourceGroupName: 'rg-siva'
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.1.427'  # Adjust SDK version as needed

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: 'dotnetcore-docs-hello-world/NuGet.Config'  # If using Azure Artifacts for private packages

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build
